# Generated by Django 3.2 on 2021-04-14 05:55

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('aadhar_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Sex', models.CharField(max_length=4)),
                ('address', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Register',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ADate', models.DateField()),
                ('ATime', models.CharField(max_length=20)),
                ('Cid', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='covaxapp.register')),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
    ]
