# Generated by Django 3.2 on 2021-04-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covaxapp', '0004_stock_supplier'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock',
            table='stock',
        ),
    ]
