# Generated by Django 3.2 on 2021-04-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covaxapp', '0006_remove_register_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Sex',
            field=models.CharField(max_length=6),
        ),
    ]
